project:
  type: website
  output-dir: docs/

website:
  site-url: https://shannonrumsey.github.io/
  title: "shannonrumsey"
  navbar:
    title: false
    search: false
    
    right:
      - href: index.qmd
        text: Home
      - href: cv.qmd
      - text: CV
      - href: blog.qmd
      - text: Deep Dives
      - href: Resume.pdf
        text: Resume
      - icon: github
        href: https://github.com/shannonrumsey
      - icon: linkedin
        href: https://www.linkedin.com/in/shannon-rumsey/
      - icon: envelope
        href: shannonalmyrumsey@gmail.com
    collapse: true
  back-to-top-navigation: false
  page-footer:
    border: false
    background: light
    right: 
      - icon: github
        href: https://github.com/shannonrumsey
      - icon: linkedin
        href: https://www.linkedin.com/in/shannon-rumsey/
      - icon: envelope
        href: mailto::shannonalmyrumsey@gmail.com


format:
  html:
    theme: 
      - custom_theme.scss
    toc: true

editor: visual

